# Generated by Django 4.2.10 on 2024-02-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mejbour', '0002_objetperdu_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetperdu',
            name='objet_trouve',
            field=models.BooleanField(default=False),
        ),
    ]
